language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
before_install:
  - npm install -g npm
before_script:
  - npm install 
after_script:
  - npm run coveralls
notifications:
  email: false
